=== Rohit2147160/WSDCAT1/ems.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Company">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name ="empName" type="xs:string"/>
							<xs:element name="empAge" type ="xs:integer"/>
							<xs:element name ="empSalary" type="sal"/>
							<xs:element name="empEmail"  type="xs:string"/>
							<xs:element name="empPhonenum" type="xs:integer"/>
							<xs:element name="empDesignation" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="sal">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="50000"/>
    	<xs:maxExclusive value="200000"/>
    </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Rohit2147160/WSDCAT1/ems.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ems.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ems.xsd">


<Employee id="123">
   <empName>Rohit</empName>
   <empAge>28</empAge>
   <empSalary>100000</empSalary>
   <empEmail>rohitp2203@gmail.com</empEmail>
   <empPhonenum>6355380271</empPhonenum>
   <empDesignation>SDE-1</empDesignation>
</Employee>

<Employee id="246">
   <empName>Mohit</empName>
   <empAge>37</empAge>
   <empSalary>50000</empSalary>
   <empEmail>mohit@gmail.com</empEmail>
   <empPhonenum>8884222885</empPhonenum>
   <empDesignation>SDE-II</empDesignation>
</Employee>


<Employee id="789">
   <empName>Ranjeet</empName>
   <empAge>52</empAge>
   <empSalary>150000</empSalary>
   <empEmail>topgun@gmail.com</empEmail>
   <empPhonenum>7892537679</empPhonenum>
   <empDesignation>SDE-III</empDesignation>
</Employee>


<Employee id="632">
   <empName>Addya</empName>
   <empAge>33</empAge>
   <empSalary>900000</empSalary>
   <empEmail>addya@gmail.com</empEmail>
   <empPhonenum>8884004885</empPhonenum>
   <empDesignation>SDE-1</empDesignation>
</Employee>


<Employee id="549">
   <empName>Deepti</empName>
   <empAge>44</empAge>
   <empSalary>900000</empSalary>
   <empEmail>deepti@gmail.com</empEmail>
   <empPhonenum>7892581898</empPhonenum>
   <empDesignation>SDE-2</empDesignation>
</Employee>



</Company>
